### ISSUE TITLE
Prefixes and file naming

### ISSUE THREAD

**Issue by apkoponen** [justingreerbbi/WP-REST-API-OAuth-2.0-Server#13]
**Prefixes**

The README defines the function prefix:

> Function naming convention - All functions will need to be prefixed properly. Function prefix is oauth2_.

However we should also define the following prefixes:
- Class prefix ("OAuth2_" ?)
- Textdomain ("oauth2" ?)
- Hook prefix ("oauth2_" ?)
- Error code prefix for plugin specific error codes for the REST API ("oauth2_" ?)
- Options prefix ("oauth2_" ?)

**File naming convetions**

You seems to use "class." in the beginning of your filenames that have. I'd prefer "class-", which is more WP-ish.

**Comment by justingreerbbi** [comment]
When starting the project, I was thinking of a generic OAuth2 server hints the OAuth2 everywhere. Now, that the plugin has morphed and has more direction we can start renaming and refactoring as needed.

I run the other WordPress OAuth Server and prefix with OAuth2 as well as _wo. To prevent clashing we can use the following format:

- Class Prefix "WP_Rest_OAuth2_" 
- Textdomain "wp_rest_oauth2"
- Hook prefix "wp_rest_oauth2_"
- Options "wp_rest_oauth2_"
- Anything not mentioned that does not require camel case use "wp_rest_oauth2_"
