### ISSUE TITLE
Error handling

### ISSUE THREAD

**Issue by apkoponen** [justingreerbbi/WP-REST-API-OAuth-2.0-Server#14]
How should we handle errors?

WP-API uses WP_Errors for this: http://v2.wp-api.org/extending/adding/#return-value. You're using a custom error array.

WP_Errors have the benefit that they can be transfered from bottom up and returned as is.

**Comment by apkoponen** [comment]
It seems that the error codes in the OAuth 2.0 spec are quite strict, so I think we should return WP_Errors from components and make the appropriate changes in the actual endpoints endpoint.

**Comment by apkoponen** [comment]
Seems to me that we will not be able to use any of the rest_register route "args" if we will opt to use error messages that differ from WP_Error. validate_callback failures will always result in a WP_Error that is returned to the user and cannot be filtered.

It seems that there is no way to override the used WP_REST_Request with our own that would return something different on from has_valid_params().

**Comment by justingreerbbi** [comment]
We will just have to handle the errors ourselves and not use any of the wp_error stuff directly.

**Comment by apkoponen** [comment]
OK. What about functions like get_token that returns a token. Should it return a WP_Error (as it currently does in my branch) with the corresponding error message or just null?

**Comment by justingreerbbi** [comment]
We should look into making our own error object. This way we can extend it in the future to include hooks that may be needed for other plugin integration. WP_Error is just a wrapper so we could mimic is and tweak to our needs. OAuth2_Error or something that would extend OAuth2_Response_Controller. 

I have not looked at it just yet in depth, and I am just spit balling here.

**Comment by apkoponen** [comment]
OK. I'll return WP_Errors and then we can change it to whatever we like.
