### ISSUE TITLE
Should we hash credentials to the DB

### ISSUE THREAD

**Issue by apkoponen** [justingreerbbi/WP-REST-API-OAuth-2.0-Server#18]
RFC 6819 "OAuth 2.0 Threat Model and Security Considerations" suggests that we should not store credentials (such as access tokens) as clear text to the DB (https://tools.ietf.org/html/rfc6819#section-5.1.4.1.3) and that we should encrypt them using an asymmetric algorithm. This prevents the token from being stolen from DB (which is quite likely in WordPress context).

I would suggest that we hash all tokens and authorization codes with `wp_hash`. This makes it possible to query them, if we know the original token/code.

With consumer secret we have the problem that it seems that there is no symmetric hashing method available out of the box. We need to be able to decrypt the hash, because we need to show it to the user.

**Comment by justingreerbbi** [comment]
I agree. Although this would slow process it would be beneficial in the event of a compromise. Good thinking on this. I completely glazed over the hashing.

`wp_hash` would work great since all tokens and codes are invalidated one a password or salt change anyways.

**Comment by apkoponen** [comment]
Any ideas on the Consumer Secret issue? The current storage example follows the OAuth1 implementation, where there is no hashing, which is pretty bad. Hashing the tokens helps a bit, as it prevents getting full admin credentials from DB (Client ID + Secret + Admin Access Token = Full access to everything that REST API provides).

**Comment by justingreerbbi** [comment]
If one has access to to the DB, they have complete access to everything. This includes REST API. Hashing is not a bad idea since it is best practice for anything data being store (sensitive or not) but storing in plain text or encrypted makes little difference.

**Comment by apkoponen** [comment]
That is true if they have direct access (credentials, a full SQL injection). However, often the access is limited and caused by certain issues. E.g. there could be a "WP Browse metas" plugin that would reveal all the metas for a post without checking the post type etc. This could be available for e.g. Editors (I have no problem believing someone would allow it). Then the attacker could just loop through all post IDs until one of them is a consumer and get the secret from there. In these type of scenarios the attacker won't have access to salts, which will make the decryption a lot harder => using a small attack vector like this is less beneficial.

**Comment by justingreerbbi** [comment]
I am all for hashing everything if we can direct indexing for matching. The consumer secret can be hashed as well since we will know the client ID and can use it as the index.

**Comment by apkoponen** [comment]
The problem with hashing the consumer secret is that is has to be shown on the consumer admin page so that the person who made the consumer (e.g. mobile app) can copy it to their configs.

**Comment by justingreerbbi** [comment]
True. If encrypting the secret is that important, them maybe we only show the secret once before it is hashed and leave it to the user to store this in a safe place.

**Comment by apkoponen** [comment]
Hmm... That decreases the UX a bit and probably results in unnecessary secret regeneration. I feel that a symmetric encryption would be a suitable compromise between the possible security implications and security, but if it's not an option, we'll have to assess whether there exists any real attack vectors. I'll go through the threath model, but the only one I've spotted yet is the ability to misuse an authorization code, but this would probably some sort of eaves dropping and a 30s window.

**Comment by justingreerbbi** [comment]
We "could" use something like AES to encrypt using a current salt value. This would allow for encrypt in the DB but show text in UI. Now with this said, this is a bit overkill because the the salt is stored on the server as well.

Maybe a pin number to show the secret. Shoot me down anytime. I am just spit balling.

**Comment by apkoponen** [comment]
I have been thinking about this and reading the OAuth 2.0 spec and Threat Model. Since the client_secret is essentially a password (used for authentication in combination with client_id) we should threat it as such ad teach our users to do the same. That's why I think your earlier suggestion is good:

> True. If encrypting the secret is that important, them maybe we only show the secret once before it is hashed and leave it to the user to store this in a safe place.

This is similar to what users do with their own passwords. If this is okay I will implement it to my branch.

**Comment by justingreerbbi** [comment]
I think this will work just fine.
