### ISSUE TITLE
Scoping

### ISSUE THREAD

**Issue by apkoponen** [justingreerbbi/WP-REST-API-OAuth-2.0-Server#19]
FYI, for the purpose of my Thesis study I will need to implement the use of "scopes". I will most likely do this using a low priority (9999) filter to current_user_can. It will take the users capabilities and the capabilities in the token and allow only the capabilities that are in the intersection of these two.

Do you have a better approach in mind (I don't). The problem with this approach is that it can be overwritten (even unintentionally) using a lower priority on the filter.

If you don't think this approach is good enough for the public implementation, I'll just keep the feature in my own branch.

**Comment by justingreerbbi** [comment]
We could very well create a mapping class to handle the scope >< user_caps. For example, we create a new role (IE. WO_BASIC) and assign caps to that. All requests default to "WO_BASIC" unless otherwise requested in the authorization flow.

IMO, this a bit overkill since REST handles this already but for your project, I am not opposed to having a separate branch that uses ROLE/SCOPES.

**Comment by apkoponen** [comment]
What do you mean by

>  REST handles this already

?

**Comment by justingreerbbi** [comment]
Rest handles roles already. A subscriber can not create a new post using REST. An Editor can not change any settings using REST. If you need to use the term "Scopes" you could map them roles and call it a day

**Comment by apkoponen** [comment]
Okay, I knew that and it's okay. 

The problem is that one of the problems of the traditional client-server paradigm (where the client uses the credentials of the user in order to access the user's resources) that OAuth 2.0 is trying to solve is: "How can I allow a third party to access only some of my resources?"

What I'm after with the scopes is something like this: There is a WordPress site RateMyFoo.com where an Editor is responsible for moderating comments (required capability: moderate_comments). A WordPress Mobile company SuperCommentModerator.app has just released a mobile app that can be used for one single thing: Moderating the comments on a WordPress site (through the REST API). The Editor wants to allow this app to moderate comments on the site, but nothing else. In addition, these moderation actions should be logged for the Editor user. So rather than creating a new user and a role (e.g. User EditorOnlyModerateComments with the role "Comment Moderator") the SuperCommentModerator.app could just request an access token through our plugin with the scope moderate_comments. Then the access token would belong to the Editor, but it would only grant the capability moderate_comments.

This is exactly what e.g. Facebook does with permissions (https://developers.facebook.com/docs/facebook-login/permissions) and Google does with scopes (https://developers.google.com/identity/protocols/googlescopes).

What I'm after here is that if WordPress is to become the "operating system of the Web" etc. there will be big services built with WordPress that will have Apps that will need different scopes that need to be granted by the user. Creating a custom role and a user by the admin will not be an option in many of these scenarios.

E.g. if you'd like to authorize an app to just edit you posts but not delete them, you can't do it by creating a new user, because the new user won't be the owner of  your posts.
