### ISSUE TITLE
is_user_logged_in() issue

### ISSUE THREAD

**Issue by justingreerbbi** [justingreerbbi/WP-REST-API-OAuth-2.0-Server#8]
In feature-justin branch, I have setup a schrub run of my idea but soon ran into issues checking if the user is logged in or not (to present the login screen when using authorize endpoint). 

I believe the issue is that `is_user_logged_in` does not work because `wp_get_current_user` is not set yet. 

We need a way to check if the user is logged in during a custom route endpoint or `/oauth2/v1/authorize` will not be able to work as needed.

**Comment by justingreerbbi** [comment]
Further investigation results in the authorize endpoint now being able to be ran through the REST API. :bummer:  We will need to manually do the authorize endpoint. Token endpoint might still be able to be used.

**Comment by apkoponen** [comment]
I believe the OAuth1 version handles this by hooking into `determine_current_user` https://github.com/WP-API/OAuth1/blob/master/oauth-server.php#L77 and then handling the authentication if the logged in user does not yet exists https://github.com/WP-API/OAuth1/blob/master/lib/class-wp-rest-oauth1.php#L166.

**Comment by justingreerbbi** [comment]
I am going to play around with it and see what we can come up with. I would love to use the route api and keep it contained.

**Comment by justingreerbbi** [comment]
Good call! That was what was needed. Closing now.
